# Generated by Django 3.0 on 2023-12-04 16:05

from django.db import migrations


def forwards(apps, schema_editor):
    try:
        OldAddress = apps.get_model("oc_lettings_site", "Address")
        OldLetting = apps.get_model("oc_lettings_site", "Letting")
    except LookupError:
        return

    NewAddress = apps.get_model("lettings", "Address")
    NewLetting = apps.get_model("lettings", "Letting")

    for old_address in OldAddress.objects.all():
        new_address = NewAddress.objects.create(
            number=old_address.number,
            street=old_address.street,
            city=old_address.city,
            state=old_address.state,
            zip_code=old_address.zip_code,
            country_iso_code=old_address.country_iso_code
        )
        old_letting = OldLetting.objects.get(address=old_address)
        NewLetting.objects.create(
            id=old_letting.id,
            title=old_letting.title,
            address=new_address
        )

class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
