version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.12.1
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run Linting
          command: flake8 .
      - run:
          name: Run Tests and Coverage
          command: |
            coverage run manage.py test
            coverage report -m --fail-under=80

  build-and-push-docker:
    docker:
      - image: cimg/python:3.12.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t ghostdogthe1/python:${CIRCLE_SHA1} .
      - run:
          name: Log in to Docker Hub
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push Docker Image to Docker Hub
          command: docker push ghostdogthe1/python:${CIRCLE_SHA1}

workflows:
  version: 2
  build-and-test-workflow:
    jobs:
      - build-and-test
      - build-and-push-docker:
          requires:
            - build-and-test
