version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.12.1
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run Linting
          command: flake8 .
      - run:
          name: Run Tests and Coverage
          command: |
            coverage run manage.py test
            coverage report -m --fail-under=80

workflows:
  version: 2
  build-and-test-workflow:
    jobs:
      - build-and-test
